### ISSUE TITLE
flocker-node: receive global state and new configuration and then execute all necessary actions on local node

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#12]
flocker-node is the CLI (later a daemon) that runs on each node and manages it.

Once flocker-cli has received new config and figured out existing configuration, it can tell this tool (on each node) to do necessary local changes to make this configuration work.

Blocked on:
- [x] Structured config object from yaml config blobs - #203
- [x] Learn current local state - #209 
- [x] Start/stop containers - #252  
- [x] Create external ports configuration #247
- [ ] Create, push or wait for volumes, and expose/unexpose as necessary #272
