### ISSUE TITLE
flocker-cli deploy: entry point to orchestration management

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#19]
Blocked by:
- [x] #203 model config from yaml config blobs
- [x] #220 read and validate deployment config
- [x] #221 configure ssh on all nodes

Take application configuration and deployment configuration. Connects to all nodes, asks for their local state, combines it into global current state and then tells all nodes to do what is necessary to change to new configuration.

```
laptop$ cat deploy.cfg
{"version": 1, "mysql-hybridcluster": {"node": "node1"}, {"site-hybridcluster.com": {"node": "node2"}}

laptop$ cat app.cfg
{"version": 1,
 "mysql-hybridcluster": {"image": "hybridlogic/mysql5.9", "volume": "/var/run/mysql"},
 "site-hybridcluster.com": {
    "image": "hybridlogic/web",
    "volume": "/var/log",
    "internal_links": {3306: {"container": "mysql-hybridcluster", "port": 3306}},
    "external_links": {"external": 80, "internal": 80},
 }
}

laptop$ flocker-cli go deploy.cfg app.cfg
  # ssh node1 flocker-node inspect-local-state
  #   {}
  # ssh node2 flocker-node inspect-local-state
  #   {}

  # CURRENT_CONFIG={"node1": {}, "node2": {}}
  # DEPLOY_CFG=$(cat deploy.cfg)
  # APP_CFG=$(cat app.cfg)
  # ssh node1 flocker-node change-local-state "${CURRENT_CONFIG}" "${DEPLOY_CFG}" "${APP_CFG}"
  # ssh node2 flocker-node change-local-state "${CURRENT_CONFIG}" "${DEPLOY_CFG}" "${APP_CFG}"
```
