### ISSUE TITLE
Create/handoff/wait for/expose volumes as necessary based on configuration changes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#272]
`flocker-changestate` should determine whether it needs to create, handoff, wait for and then expose/unexpose volumes, based on current and desired configuration.

This is largely a big enough chunk of work that it will be split into additional sub-issues at some point (#311 is the first sub-task).

Blocked on:
- [x] #274 Get rid of namespacing prefix on container name
- [x] #271 configuration for volumes
- [x] #279 Get access to other nodes' state when applying configuration changes
