### ISSUE TITLE
Clone (branch?) the current environment under a new name

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#733]
We want to be able to clone the current environment and have a new set of applications and volumes running. Possibly "branch" is a better name? Decide.

This involves a new user facing command line tool `flocker-clone`. For example:

```
$ flocker-clone application.yml deployment.yml mycopy
myapp:80 available on port 5673.
mydatabase:9337 available on port 5674.
```

The basic algorithm for `flocker-clone`:
1. Run normal flocker-deploy code path.
2. Run “flocker-volume clone” for all volumes to new namespace.
3. Create in-memory copy of given configuration (application/deployment) with new namespace and new ports chosen based on result of flocker-state.
4. Run flocker-deploy code path with this new configuration.

Blocked on:
- [ ] #737 Namespaces for applications and volumes
- [ ] #738 `flocker-reportstate` includes used (and therefore allows figuring out free) TCP ports on the node
- [ ] #739 `flocker-volume clone` supports cloning volume using ZFS clone functionality
