### ISSUE TITLE
Namespacing support in flocker.node configuration and deployment logic

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#737]
In order to support cloning (https://github.com/ClusterHQ/flocker/issues/739) we need to way to distinguish original environment from clones. 
Things to solve:
1. We don't want running the deployment logic to setup the clone to stop the applications in the original environment, which is what it would do know.
2. We need to figure out how naming works; we've got original "mydatabase" and cloned "mydatabase"...

The proposed solution: namespacing.

_UPDATED BASED ON DISCUSSION IN #746:_
1. Each application and volume resides in a namespace.
2. Links happen within a namespace (although given that they use global ports for now this is irrelevant).
3. YAML config used by users will will not mention the namespace; the namespace will be communicated out-of-band.
4. Changes to state in one namespace do not interact with other namespaces.
5. Clones will have namespace names specified by the clone name.
6. `flocker-reportstate` will include all namespaces.

Blocked on:
- [x] #771 Namespacing for volumes
- [x] #772 Namespacing support around the Docker client
- [ ] #790 Namespacing support in output of `flocker-reportstate` (or maybe this can be done in parallel)
- [ ] #850 Namespacing support in `flocker.route`

This issue encompasses:
- making `flocker-changestate` accept a namespace argument (optional, defaults to "default")
- making `Deployer` aware of namespaces and `change_node_state` only operate within a specified namespace (iow it shouldn't stop containers that are running in a different namespace, it should use volumes in the specified namespace, etc)

Put another way, to resolve this ticket, make it possible to run a commands like:

```
$ flocker-changestate --namespace foo <deploy config> <app config> <cluster config> <hostname>
$ flocker-changestate --namespace bar <deploy config> <app config> <cluster config> <hostname>
```

such that containers specified by the deployment configuration given to the first command are not touched by the second command (no matter how the configurations might overlap or fail to).
