### ISSUE TITLE
Define environment variables for deployed containers

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#95]
Docker convention is to supply runtime configuration to containers as environment variables. A user must be able to define the environment for each container in the Flocker configuration.
- [x] #568 GearClient.add environment variables
- [x] #569 Environment variables in application.yml
- [x]  #586 Add environment variable support to flocker.node.Deployer.calculate_necessary_state_changes 
- [x]  #593 Documentation for applications with environment variables
